USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA UNOPTIMIZED;

CREATE OR REPLACE TABLE INSTACART_DW.UNOPTIMIZED.FLAT_ORDERS AS
SELECT
    OP.ORDER_ID,
    OP.PRODUCT_ID,
    OP.ADD_TO_CART_ORDER,
    OP.REORDERED,
    O.USER_ID,
    O.ORDER_NUMBER,
    O.ORDER_DOW,
    O.ORDER_HOUR_OF_DAY,
    O.DAYS_SINCE_PRIOR_ORDER,
    P.PRODUCT_NAME,
    P.AISLE_ID,
    P.DEPARTMENT_ID,
    A.AISLE,
    D.DEPARTMENT
FROM
(
    SELECT ORDER_ID, PRODUCT_ID, ADD_TO_CART_ORDER, REORDERED
    FROM RAW.ORDER_PRODUCTS__PRIOR
    UNION ALL
    SELECT ORDER_ID, PRODUCT_ID, ADD_TO_CART_ORDER, REORDERED
    FROM RAW.ORDER_PRODUCTS__TRAIN
) OP
JOIN RAW.ORDERS O
ON OP.ORDER_ID = O.ORDER_ID
JOIN RAW.PRODUCTS P
ON OP.PRODUCT_ID = P.PRODUCT_ID
JOIN RAW.AISLES A
ON P.AISLE_ID = A.AISLE_ID
JOIN RAW.DEPARTMENTS D
ON P.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE UPPER(TRIM(O.EVAL_SET)) != 'TEST';

SELECT COUNT(*) FROM INSTACART_DW.UNOPTIMIZED.FLAT_ORDERS;