USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA UNOPTIMIZED;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET QUERY_TAG = 'unoptimized_q1_reorder_rate';

-- Which departments and aisles have the highest reorder rates?

-- Grain: one row per department + aisle combination

SELECT
    DEPARTMENT AS DEPARTMENT_NAME,
    AISLE AS AISLE_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_ORDER_LINES,
    COUNT(DISTINCT PRODUCT_ID) AS UNIQUE_PRODUCTS,
    SUM(REORDERED) AS REORDER_COUNT,
    ROUND(AVG(REORDERED) * 100, 2) AS REORDER_RATE_PCT,
    ROUND(AVG(ADD_TO_CART_ORDER), 2) AS AVG_CART_POSITION
FROM INSTACART_DW.UNOPTIMIZED.FLAT_ORDERS
GROUP BY DEPARTMENT, AISLE
ORDER BY REORDER_RATE_PCT DESC;

ALTER SESSION UNSET QUERY_TAG;