USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA UNOPTIMIZED;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET QUERY_TAG = 'unoptimized_q2_user_frquency';

-- How do shopping behaviors differ across light vs heavy users?

-- Grain: one row per frequency segment

WITH USER_ORDERS AS (
    SELECT
        USER_ID,
        COUNT(ORDER_ID) AS TOTAL_ORDERS,
        AVG(DAYS_SINCE_PRIOR_ORDER) AS AVERAGE_DAYS_SINCE_PRIOR_ORDER
    FROM (
        SELECT DISTINCT
            USER_ID::INT AS USER_ID,
            ORDER_ID::INT AS ORDER_ID,
            DAYS_SINCE_PRIOR_ORDER::FLOAT AS DAYS_SINCE_PRIOR_ORDER
        FROM INSTACART_DW.UNOPTIMIZED.FLAT_ORDERS
    )
    GROUP BY USER_ID
),

USER_ITEMS AS (
    SELECT
        USER_ID::INT AS USER_ID,
        COUNT(*)::FLOAT / NULLIF(COUNT(DISTINCT ORDER_ID::INT), 0) AS AVG_BASKET_SIZE_PER_USER,
        SUM(REORDERED::INT) AS TOTAL_REORDERS,
        COUNT(DISTINCT PRODUCT_ID::INT) AS UNIQUE_PRODUCTS_BOUGHT,
        ROUND(AVG(REORDERED::INT) * 100, 2) AS REORDER_RATE_PCT
    FROM INSTACART_DW.UNOPTIMIZED.FLAT_ORDERS
    GROUP BY USER_ID::INT
),

USER_SEGMENT AS (
    SELECT
        CASE
            WHEN TOTAL_ORDERS BETWEEN 1 AND 4 THEN 'casual'
            WHEN TOTAL_ORDERS BETWEEN 5 AND 9 THEN 'occasional'
            WHEN TOTAL_ORDERS BETWEEN 10 AND 19 THEN 'regular'
            WHEN TOTAL_ORDERS BETWEEN 20 AND 49 THEN 'loyal'
            WHEN TOTAL_ORDERS >= 50 THEN 'power user'
        END AS SEGMENT,
        uo.USER_ID,
        uo.TOTAL_ORDERS,
        uo.AVERAGE_DAYS_SINCE_PRIOR_ORDER,
        ui.AVG_BASKET_SIZE_PER_USER,
        ui.TOTAL_REORDERS,
        ui.UNIQUE_PRODUCTS_BOUGHT,
        ui.REORDER_RATE_PCT
    FROM USER_ORDERS uo
    INNER JOIN USER_ITEMS ui
    ON uo.USER_ID = ui.USER_ID
)

SELECT
    SEGMENT,
    COUNT(*) AS USER_COUNT,
    ROUND(AVG(AVERAGE_DAYS_SINCE_PRIOR_ORDER), 1) AS AVG_DAYS_BETWEEN_ORDERS,
    ROUND(AVG(TOTAL_ORDERS), 1) AS AVG_TOTAL_ORDERS,
    ROUND(AVG(AVG_BASKET_SIZE_PER_USER), 1) AS AVG_BASKET_SIZE_PER_SEGMENT,
    ROUND(AVG(UNIQUE_PRODUCTS_BOUGHT), 1) AS AVG_UNIQUE_PRODUCTS,
    ROUND(AVG(REORDER_RATE_PCT), 2) AS AVG_REORDER_RATE_PCT
FROM USER_SEGMENT
GROUP BY SEGMENT
ORDER BY
    CASE SEGMENT
        WHEN 'casual' THEN 1
        WHEN 'occasional' THEN 2
        WHEN 'regular' THEN 3
        WHEN 'loyal' THEN 4
        WHEN 'power user' THEN 5
    END;

ALTER SESSION UNSET QUERY_TAG;