USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA UNOPTIMIZED;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET QUERY_TAG = 'unoptimized_q2_user_frquency';

-- How do shopping behaviors differ across light vs heavy users?

-- Grain: one row per frequency segment

SELECT
    SEGMENT,
    COUNT(*) AS USER_COUNT,
    ROUND(AVG(AVERAGE_DAYS_SINCE_PRIOR_ORDER), 1) AS AVG_DAYS_BETWEEN_ORDERS,
    ROUND(AVG(TOTAL_ORDERS), 1) AS AVG_TOTAL_ORDERS,
    ROUND(AVG(AVG_BASKET_SIZE_PER_USER), 1) AS AVG_BASKET_SIZE_PER_SEGMENT,
    ROUND(AVG(UNIQUE_PRODUCTS_BOUGHT), 1) AS AVG_UNIQUE_PRODUCTS,
    ROUND(AVG(DEPARTMENTS_SHOPPED), 1) AS AVG_DEPARTMENTS_SHOPPED,
    ROUND(AVG(REORDER_RATE_PCT), 2) AS AVG_REORDER_RATE_PCT
FROM (
    SELECT
        CASE
            WHEN TOTAL_ORDERS BETWEEN 1 AND 4 THEN 'casual'
            WHEN TOTAL_ORDERS BETWEEN 5 AND 9 THEN 'occasional'
            WHEN TOTAL_ORDERS BETWEEN 10 AND 19 THEN 'regular'
            WHEN TOTAL_ORDERS BETWEEN 20 AND 49 THEN 'loyal'
            WHEN TOTAL_ORDERS >= 50 THEN 'power user'
        END AS SEGMENT,
        TOTAL_ORDERS,
        AVERAGE_DAYS_SINCE_PRIOR_ORDER,
        AVG_BASKET_SIZE_PER_USER,
        TOTAL_REORDERS,
        UNIQUE_PRODUCTS_BOUGHT,
        DEPARTMENTS_SHOPPED,
        REORDER_RATE_PCT
    FROM (
        SELECT
            USER_ID,
            MAX(ORDER_NUMBER::INT) AS TOTAL_ORDERS,
            AVG(DAYS_SINCE_PRIOR_ORDER) AS AVERAGE_DAYS_SINCE_PRIOR_ORDER,
            COUNT(*) / NULLIF(COUNT(DISTINCT ORDER_ID), 0) AS AVG_BASKET_SIZE_PER_USER,
            SUM(REORDERED) AS TOTAL_REORDERS,
            COUNT(DISTINCT PRODUCT_ID) AS UNIQUE_PRODUCTS_BOUGHT,
            COUNT(DISTINCT DEPARTMENT) AS DEPARTMENTS_SHOPPED,
            ROUND(AVG(REORDERED) * 100, 2) AS REORDER_RATE_PCT
        FROM INSTACART_DW.UNOPTIMIZED.FLAT_ORDERS
        GROUP BY USER_ID
    )
)
GROUP BY SEGMENT
ORDER BY
    CASE SEGMENT
        WHEN 'casual' THEN 1
        WHEN 'occasional' THEN 2
        WHEN 'regular' THEN 3
        WHEN 'loyal' THEN 4
        WHEN 'power user' THEN 5
    END;

ALTER SESSION UNSET QUERY_TAG;