USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA UNOPTIMIZED;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET QUERY_TAG = 'unoptimized_q3_shopping_patterns';

-- When do people shop and how does basket behavior change by time?

-- Grain: one row per day_of_week + hour combination

SELECT
    CASE ORDER_DOW::INT
        WHEN 0 THEN 'Sunday'
        WHEN 1 THEN 'Monday'
        WHEN 2 THEN 'Tuesday'
        WHEN 3 THEN 'Wednesday'
        WHEN 4 THEN 'Thursday'
        WHEN 5 THEN 'Friday'
        WHEN 6 THEN 'Saturday'
    END AS DAY_OF_WEEK,
    ORDER_DOW,
    ORDER_HOUR_OF_DAY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_ITEMS,
    ROUND(COUNT(*) / NULLIF(COUNT(DISTINCT ORDER_ID), 0), 2) AS AVG_BASKET_SIZE,
    ROUND(AVG(REORDERED) * 100, 2) AS REORDER_RATE_PCT,
    RANK() OVER (
        PARTITION BY ORDER_DOW ORDER BY COUNT(DISTINCT ORDER_ID) DESC
    ) AS PEAK_RANK_WITHIN_DAY
FROM INSTACART_DW.UNOPTIMIZED.FLAT_ORDERS
GROUP BY ORDER_DOW, ORDER_HOUR_OF_DAY
ORDER BY ORDER_DOW, ORDER_HOUR_OF_DAY;

ALTER SESSION UNSET QUERY_TAG;