USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA UNOPTIMIZED;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET QUERY_TAG = 'unoptimized_q3_shopping_patterns';

-- When do people shop and how does basket behavior change by time?

-- Grain: one row per day_of_week + hour combination

SELECT
    CASE ORDER_DOW::INT
        WHEN 0 THEN 'Sunday'
        WHEN 1 THEN 'Monday'
        WHEN 2 THEN 'Tuesday'
        WHEN 3 THEN 'Wednesday'
        WHEN 4 THEN 'Thursday'
        WHEN 5 THEN 'Friday'
        WHEN 6 THEN 'Saturday'
    END AS DAY_OF_WEEK,
    ORDER_DOW::INT AS ORDER_DOW,
    ORDER_HOUR_OF_DAY::INT AS ORDER_HOUR_OF_DAY,
    COUNT(DISTINCT ORDER_ID::INT) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_LINE_ITEMS,
    ROUND(COUNT(*)::FLOAT / NULLIF(COUNT(DISTINCT ORDER_ID::INT), 0), 1) AS AVG_BASKET_SIZE,
    RANK() OVER (
        PARTITION BY ORDER_DOW::INT ORDER BY COUNT(DISTINCT ORDER_ID::INT) DESC
    ) AS PEAK_RANK_WITHIN_DAY
FROM INSTACART_DW.UNOPTIMIZED.FLAT_ORDERS
GROUP BY ORDER_DOW::INT, ORDER_HOUR_OF_DAY::INT
ORDER BY ORDER_DOW::INT, ORDER_HOUR_OF_DAY::INT;

ALTER SESSION UNSET QUERY_TAG;