-- STEP 1: Verify if a cluster key is actively defined
SELECT
    TABLE_NAME, 
    CLUSTERING_KEY, 
    AUTO_CLUSTERING_ON
FROM INSTACART_DW.INFORMATION_SCHEMA.TABLES
--
WHERE TABLE_SCHEMA = 'CORE'
AND TABLE_NAME IN ('DIM_PRODUCTS', 'AGG_USER_METRICS', 'FCT_ORDERS', 'FCT_ORDER_ITEMS');

-- STEP 2: Candidate column identification (Workload analysis)
-- FCT_ORDER_ITEMS (ORDER_DOW, ORDER_HOUR_OF_DAY, REORDERED)
-- FCT_ORDERS (ORDER_DOW, ORDER_HOUR_OF_DAY)

-- STEP 3: Virtual evaluation (Fact tables)
SELECT SYSTEM$CLUSTERING_INFORMATION('INSTACART_DW.CORE.FCT_ORDER_ITEMS', '(ORDER_DOW, ORDER_HOUR_OF_DAY, REORDERED)');
SELECT SYSTEM$CLUSTERING_INFORMATION('INSTACART_DW.CORE.FCT_ORDERS', '(ORDER_DOW, ORDER_HOUR_OF_DAY)');

-- STEP 4: Cost/Scale gate (Check table size & row counts)
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    ROUND(BYTES / (1024 * 1024), 2) AS SIZE_MB
FROM INSTACART_DW.INFORMATION_SCHEMA.TABLES
--
WHERE TABLE_SCHEMA = 'CORE'
AND TABLE_NAME IN ('DIM_PRODUCTS', 'AGG_USER_METRICS', 'FCT_ORDERS', 'FCT_ORDER_ITEMS')
ORDER BY BYTES DESC;

-- STEP 5: Architecture decision
/*
    DECISION: Do Not apply ALTER TABLE ... CLUSTER BY.
    REASON: Tables are under 1GB threshold and show low depth reduction.
*/