USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA CORE;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET QUERY_TAG = 'optimized_q1_reorder_rate';

-- Which departments and aisles have the highest reorder rates?

-- Grain: one row per department + aisle combination

SELECT
    P.DEPARTMENT_NAME AS DEPARTMENT_NAME,
    P.AISLE_NAME AS AISLE_NAME,
    COUNT(DISTINCT OI.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_LINE_ITEMS,
    COUNT(DISTINCT OI.PRODUCT_ID) AS UNIQUE_PRODUCTS,
    SUM(REORDERED) AS TOTAL_REORDERS,
    ROUND(AVG(REORDERED) * 100, 2) AS REORDER_RATE_PCT,
    ROUND(AVG(ADD_TO_CART_ORDER), 1) AS AVG_CART_POSITION
FROM INSTACART_DW.CORE.FCT_ORDER_ITEMS OI
--
JOIN INSTACART_DW.CORE.DIM_PRODUCTS P
ON OI.PRODUCT_ID = P.PRODUCT_ID
--
GROUP BY P.DEPARTMENT_NAME, P.AISLE_NAME
ORDER BY REORDER_RATE_PCT DESC;

ALTER SESSION UNSET QUERY_TAG;