USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA OPTIMIZED;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET QUERY_TAG = 'optimized_q2_user_frquency';

-- How do shopping behaviors differ across light vs heavy users?

-- Grain: one row per frequency segment

SELECT
    FREQUENCY_SEGMENT,
    COUNT(*) AS USER_COUNT,
    ROUND(AVG(AVG_DAYS_BETWEEN_ORDERS), 1) AS AVG_DAYS_BETWEEN_ORDERS,
    ROUND(AVG(TOTAL_ORDERS), 1) AS AVG_TOTAL_ORDERS,
    ROUND(AVG(AVG_BASKET_SIZE), 1) AS AVG_BASKET_SIZE_PER_SEGMENT,
    ROUND(AVG(UNIQUE_PRODUCTS_BOUGHT), 1) AS AVG_UNIQUE_PRODUCTS,
    ROUND(AVG(REORDER_RATE_PCT), 2) AS AVG_REORDER_RATE_PCT
FROM INSTACART_DW.CORE.DIM_USERS
GROUP BY FREQUENCY_SEGMENT
ORDER BY
    CASE FREQUENCY_SEGMENT
        WHEN 'casual' THEN 1
        WHEN 'occasional' THEN 2
        WHEN 'regular' THEN 3
        WHEN 'loyal' THEN 4
        WHEN 'power user' THEN 5
    END;

ALTER SESSION UNSET QUERY_TAG;