USE ROLE SYSADMIN;
USE DATABASE INSTACART_DW;
USE SCHEMA MONITORING;
USE WAREHOUSE INSTACART_WH;

-- Create log table
CREATE OR REPLACE TABLE INSTACART_DW.MONITORING.QUERY_PERF_LOG (
    _LOGGED_AT TIMESTAMP_NTZ,
    PHASE VARCHAR(30),
    QUERY_LABEL VARCHAR(60),
    RUNTIME_SEC FLOAT,
    GB_SCANNED FLOAT,
    PCT_PARTITIONS_HIT FLOAT,
    ROWS_PRODUCED NUMBER,
    GB_READ_FROM_RESULT FLOAT,
    GB_SPILLED_TO_LOCAL_STORAGE FLOAT,
    GB_SPILLED_TO_REMOTE_STORAGE FLOAT
);

-- Monitoring - SNOWFLAKE.ACCOUNT_USAGE
INSERT INTO INSTACART_DW.MONITORING.QUERY_PERF_LOG
    (_LOGGED_AT, PHASE, QUERY_LABEL, RUNTIME_SEC, GB_SCANNED, PCT_PARTITIONS_HIT, ROWS_PRODUCED, GB_READ_FROM_RESULT, GB_SPILLED_TO_LOCAL_STORAGE, GB_SPILLED_TO_REMOTE_STORAGE)
SELECT
    CURRENT_TIMESTAMP() AS _LOGGED_AT,
    'BEFORE' AS PHASE,
    QUERY_TAG AS QUERY_LABEL,
    ROUND(EXECUTION_TIME / 1000, 2) AS RUNTIME_SEC,
    ROUND(BYTES_SCANNED / 1e9, 3) AS GB_SCANNED,
    ROUND(PARTITIONS_SCANNED / NULLIF(PARTITIONS_TOTAL, 0) * 100, 1) AS PCT_PARTITIONS_HIT,
    ROWS_PRODUCED,
    ROUND(BYTES_READ_FROM_RESULT / 1e9, 3) AS GB_READ_FROM_RESULT,
    ROUND(BYTES_SPILLED_TO_LOCAL_STORAGE / 1e9, 3) AS GB_SPILLED_TO_LOCAL_STORAGE,
    ROUND(BYTES_SPILLED_TO_REMOTE_STORAGE / 1e9, 3) AS GB_SPILLED_TO_REMOTE_STORAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE
    EXECUTION_TIME > 0
    AND BYTES_SCANNED > 0
    AND DATABASE_NAME = 'INSTACART_DW'
    AND EXECUTION_STATUS = 'SUCCESS'
    AND QUERY_TYPE = 'SELECT'
    AND QUERY_TAG LIKE 'unoptimized_%'
ORDER BY START_TIME DESC;

SELECT *
FROM INSTACART_DW.MONITORING.QUERY_PERF_LOG
WHERE PHASE = 'BEFORE'
ORDER BY _LOGGED_AT, QUERY_LABEL;