USE ROLE SYSADMIN;
USE DATABASE INSTACART_DW;
USE SCHEMA MONITORING;
USE WAREHOUSE INSTACART_WH;

-- After Star Schema
INSERT INTO INSTACART_DW.MONITORING.QUERY_PERF_LOG
    (START_TIME, PHASE, QUERY_LABEL, RUNTIME_SEC, GB_SCANNED, PARTITIONS_SCANNED, PARTITIONS_TOTAL, PCT_PARTITIONS_HIT, ROWS_PRODUCED, GB_READ_FROM_RESULT, GB_SPILLED_TO_LOCAL_STORAGE, GB_SPILLED_TO_REMOTE_STORAGE)
SELECT
    START_TIME,
    'AFTER' AS PHASE,
    QUERY_TAG AS QUERY_LABEL,
    ROUND(EXECUTION_TIME / 1000, 2) AS RUNTIME_SEC,
    ROUND(BYTES_SCANNED / 1e9, 3) AS GB_SCANNED,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    ROUND(PARTITIONS_SCANNED / NULLIF(PARTITIONS_TOTAL, 0) * 100, 1) AS PCT_PARTITIONS_HIT,
    ROWS_PRODUCED,
    ROUND(BYTES_READ_FROM_RESULT / 1e9, 3) AS GB_READ_FROM_RESULT,
    ROUND(BYTES_SPILLED_TO_LOCAL_STORAGE / 1e9, 3) AS GB_SPILLED_TO_LOCAL_STORAGE,
    ROUND(BYTES_SPILLED_TO_REMOTE_STORAGE / 1e9, 3) AS GB_SPILLED_TO_REMOTE_STORAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE
    EXECUTION_TIME > 0
    AND BYTES_SCANNED > 0
    AND DATABASE_NAME = 'INSTACART_DW'
    AND EXECUTION_STATUS = 'SUCCESS'
    AND QUERY_TYPE = 'SELECT'
    AND QUERY_TAG LIKE 'optimized_%'
ORDER BY START_TIME DESC;


-- Side by Side Before vs After
WITH BEFORE_METRICS AS (
    SELECT
        REPLACE(QUERY_LABEL, 'unoptimized_', '') AS QUERY,
        RUNTIME_SEC,
        GB_SCANNED,
        PCT_PARTITIONS_HIT,
        ROWS_PRODUCED
    FROM INSTACART_DW.MONITORING.QUERY_PERF_LOG
    WHERE PHASE = 'BEFORE'
),

AFTER_METRICS AS (
    SELECT
        REPLACE(QUERY_LABEL, 'optimized_', '') AS QUERY,
        RUNTIME_SEC,
        GB_SCANNED,
        PCT_PARTITIONS_HIT,
        ROWS_PRODUCED
    FROM INSTACART_DW.MONITORING.QUERY_PERF_LOG
    WHERE PHASE = 'AFTER'
)

SELECT
    B.QUERY,
    B.RUTIME_SEC AS RUNTIME_BEFORE_SEC,
    A.RUTIME_SEC AS RUNTIME_AFTER_SEC,
    ROUND((1 - A.RUNTIME_SEC / NULLIF(B.RUNTIME_SEC,0)) * 100, 2) AS RUNTIME_IMPROVEMENT_PCT,
    B.GB_SCANNED AS GB_BEFORE,
    A.GB_SCANNED AS GB_AFTER,
    ROUND((1 - A.GB_SCANNED / NULLIF(B.GB_SCANNED,0)) * 100, 2) AS GB_REDUCTION_PCT,
    B.PCT_PARTITIONS_HIT AS PCT_PARTITIONS_HIT_BEFORE,
    A.PCT_PARTITIONS_HIT AS PCT_PARTITIONS_HIT_AFTER,
    B.ROWS_PRODUCED AS ROWS_PRODUCED_BEFORE,
    A.ROWS_PRODUCED AS ROWS_PRODUCED_AFTER
FROM BEFORE_METRICS B
--
JOIN AFTER_METRICS A
ON B.QUERY = A.QUERY
--
ORDER BY B.QUERY;