SELECT
    DEPARTMENT_NAME,
    AISLE_NAME,
    COUNT(DISTINCT ORDER_ID::INT) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_ORDER_LINES,
    COUNT(DISTINCT fct.PRODUCT_ID::INT) AS UNIQUE_PRODUCTS,
    SUM(REORDERED::INT) AS REORDER_COUNT,
    ROUND(AVG(REORDERED::INT) * 100, 2) AS REORDER_RATE_PCT,
    ROUND(AVG(ADD_TO_CART_ORDER::INT), 2) AS AVG_CART_POSITION
FROM {{ ref('fct_order_items') }} fct
JOIN {{ ref('dim_products') }} dim
ON fct.product_id = dim.product_id
GROUP BY DEPARTMENT_NAME, AISLE_NAME
ORDER BY REORDER_RATE_PCT DESC
