version: 2

sources:
  - name: raw
    database: INSTACART_DW
    schema: RAW
    tables:
      - name: orders
      - name: order_products__prior
      - name: order_products__train
      - name: products
      - name: aisles
      - name: departments