USE ROLE ACCOUNTADMIN;

-- Create Storage Integration
CREATE STORAGE INTEGRATION IF NOT EXISTS AZURE_INSTACART_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = AZURE
  ENABLED = TRUE
  AZURE_TENANT_ID = '<YOUR_AZURE_TENANT_ID>'
  STORAGE_ALLOWED_LOCATIONS = ('azure://<YOUR_STORAGE_ACCOUNT>.blob.core.windows.net/instacart-raw/');

GRANT USAGE ON INTEGRATION AZURE_INSTACART_INT TO ROLE SYSADMIN;

-- Create Warehouse, Database, and Schemas
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS INSTACART_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS INSTACART_DW;

-- Bronze Layer (tables)
CREATE SCHEMA IF NOT EXISTS INSTACART_DW.RAW;

-- Silver Layer (views)
CREATE SCHEMA IF NOT EXISTS INSTACART_DW.STAGING;

-- Gold Layer (tables)
CREATE SCHEMA IF NOT EXISTS INSTACART_DW.CORE;

-- Unoptimized baseline (flat table)
CREATE SCHEMA IF NOT EXISTS INSTACART_DW.UNOPTIMIZED;

-- Performance monitoring (tables)
CREATE SCHEMA IF NOT EXISTS INSTACART_DW.MONITORING;

-- Access control for dbt cloud connects as SYSADMIN
GRANT USAGE ON DATABASE INSTACART_DW TO ROLE SYSADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSTACART_DW TO ROLE SYSADMIN;
GRANT ALL ON ALL TABLES IN DATABASE INSTACART_DW TO ROLE SYSADMIN;
GRANT ALL ON FUTURE TABLES IN DATABASE INSTACART_DW TO ROLE SYSADMIN;