USE ROLE SYSADMIN;
USE WAREHOUSE INSTACART_WH;
USE DATABASE INSTACART_DW;
USE SCHEMA RAW;

-- File Format
CREATE OR REPLACE FILE FORMAT INSTACART_DW.RAW.FF_INSTACART_CSV
  TYPE = CSV
  SKIP_HEADER = 1 
  FIELD_DELIMITER = ','
  RECORD_DELIMITER = '\n'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

-- Map Stage to Storage Integration
CREATE OR REPLACE STAGE INSTACART_DW.RAW.STG_ADLS_INSTACART
  STORAGE_INTEGRATION = AZURE_INSTACART_INT
  URL = 'azure://instacartdatalake.blob.core.windows.net/instacart-raw/'
  FILE_FORMAT = INSTACART_DW.RAW.FF_INSTACART_CSV;