use role SYSADMIN;
use database INSTACART_DW;
use schema RAW;

-- 1. Bronze Layer Tables

create or replace table INSTACART_DW.RAW.AISLES (
    AISLE_ID VARCHAR,
    AISLE VARCHAR,
    _FILE_NAME VARCHAR,
    _ROW_NUMBER NUMBER,
    _LOADED_AT TIMESTAMP_NTZ
);

create or replace table INSTACART_DW.RAW.DEPARTMENTS (
    DEPARTMENT_ID VARCHAR,
    DEPARTMENT VARCHAR,
    _FILE_NAME VARCHAR,
    _ROW_NUMBER NUMBER,
    _LOADED_AT TIMESTAMP_NTZ
);

create or replace table INSTACART_DW.RAW.PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    AISLE_ID VARCHAR,
    DEPARTMENT_ID VARCHAR,
    _FILE_NAME VARCHAR,
    _ROW_NUMBER NUMBER,
    _LOADED_AT TIMESTAMP_NTZ
);

create or replace table INSTACART_DW.RAW.ORDERS (
    ORDER_ID VARCHAR,
    USER_ID VARCHAR,
    EVAL_SET VARCHAR,
    ORDER_NUMBER VARCHAR,
    ORDER_DOW VARCHAR,
    ORDER_HOUR_OF_DAY VARCHAR,
    DAYS_SINCE_PRIOR_ORDER VARCHAR,
    _FILE_NAME VARCHAR,
    _ROW_NUMBER NUMBER,
    _LOADED_AT TIMESTAMP_NTZ
);

create or replace table INSTACART_DW.RAW.ORDER_PRODUCTS__TRAIN (
    ORDER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    ADD_TO_CART_ORDER VARCHAR,
    REORDERED VARCHAR,
    _FILE_NAME VARCHAR,
    _ROW_NUMBER NUMBER,
    _LOADED_AT TIMESTAMP_NTZ
);

create or replace table INSTACART_DW.RAW.ORDER_PRODUCTS__PRIOR (
    ORDER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    ADD_TO_CART_ORDER VARCHAR,
    REORDERED VARCHAR,
    _FILE_NAME VARCHAR,
    _ROW_NUMBER NUMBER,
    _LOADED_AT TIMESTAMP_NTZ
);


-- 2. Ingestion (COPY INTO)

COPY INTO INSTACART_DW.RAW.ORDERS (ORDER_ID, USER_ID, EVAL_SET, ORDER_NUMBER, ORDER_DOW, ORDER_HOUR_OF_DAY, DAYS_SINCE_PRIOR_ORDER, _FILE_NAME, _ROW_NUMBER, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
    FROM @INSTACART_DW.RAW.STG_ADLS_INSTACART/orders.csv
)
FILE_FORMAT = (FORMAT_NAME = INSTACART_DW.RAW.FF_INSTACART_CSV)
ON_ERROR = ABORT_STATEMENT;

COPY INTO INSTACART_DW.RAW.ORDER_PRODUCTS__PRIOR (ORDER_ID, PRODUCT_ID, ADD_TO_CART_ORDER, REORDERED, _FILE_NAME, _ROW_NUMBER, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
    FROM @INSTACART_DW.RAW.STG_ADLS_INSTACART/order_products__prior.csv
)
FILE_FORMAT = (FORMAT_NAME = INSTACART_DW.RAW.FF_INSTACART_CSV)
ON_ERROR = ABORT_STATEMENT;

COPY INTO INSTACART_DW.RAW.ORDER_PRODUCTS__TRAIN (ORDER_ID, PRODUCT_ID, ADD_TO_CART_ORDER, REORDERED, _FILE_NAME, _ROW_NUMBER, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
    FROM @INSTACART_DW.RAW.STG_ADLS_INSTACART/order_products__train.csv
)
FILE_FORMAT = (FORMAT_NAME = INSTACART_DW.RAW.FF_INSTACART_CSV)
ON_ERROR = ABORT_STATEMENT;

COPY INTO INSTACART_DW.RAW.AISLES (AISLE_ID, AISLE, _FILE_NAME, _ROW_NUMBER, _LOADED_AT)
FROM (
    SELECT $1, $2, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
    FROM @INSTACART_DW.RAW.STG_ADLS_INSTACART/aisles.csv
)
FILE_FORMAT = (FORMAT_NAME = INSTACART_DW.RAW.FF_INSTACART_CSV)
ON_ERROR = ABORT_STATEMENT;

COPY INTO INSTACART_DW.RAW.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT, _FILE_NAME, _ROW_NUMBER, _LOADED_AT)
FROM (
    SELECT $1, $2, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
    FROM @INSTACART_DW.RAW.STG_ADLS_INSTACART/departments.csv
)
FILE_FORMAT = (FORMAT_NAME = INSTACART_DW.RAW.FF_INSTACART_CSV)
ON_ERROR = ABORT_STATEMENT;

COPY INTO INSTACART_DW.RAW.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, AISLE_ID, DEPARTMENT_ID, _FILE_NAME, _ROW_NUMBER, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
    FROM @INSTACART_DW.RAW.STG_ADLS_INSTACART/products.csv
)
FILE_FORMAT = (FORMAT_NAME = INSTACART_DW.RAW.FF_INSTACART_CSV)
ON_ERROR = ABORT_STATEMENT;